.PHONY: clean All

All:
	@echo "----------Building project:[ Lab_6A - Debug ]----------"
	@cd "Lab_6A" && "$(MAKE)" -f  "Lab_6A.mk"
clean:
	@echo "----------Cleaning project:[ Lab_6A - Debug ]----------"
	@cd "Lab_6A" && "$(MAKE)" -f  "Lab_6A.mk" clean
